// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Day1.Models;

public partial class Course
{
    public int? CRS_ID { get; set; }

    [Required]
    [StringLength(25,MinimumLength =5,ErrorMessage ="name must be in range between 5 and 25 chars")]
    public string Cname { get; set; }

    [Required]
    [Range(10,50,ErrorMessage ="duration must be in between 10 and 50")]
	public int Duration { get; set; }

    public virtual ICollection<Lab>? Labs { get; set; } = new List<Lab>();

    public virtual ICollection<Instructor>? INs { get; set; } = new List<Instructor>();
}