// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Day1.Models;

public partial class Lab
{
    public int LID { get; set; }

    public string Lab_Location { get; set; }

    public int? Capacity { get; set; }

    public int CID { get; set; }

    public virtual Course CIDNavigation { get; set; }
}